#!/bin/sh
./ws_client.sh control  &>/dev/null &
 ./ws_client.sh abstract  &>/dev/null &
 ./ws_client.sh data  &>/dev/null &
 ./ws_client.sh control  &>/dev/null &
 ./ws_client.sh abstract  &>/dev/null &
 ./ws_client.sh data  &>/dev/null &
 ./ws_client.sh control  &>/dev/null &
 ./ws_client.sh control  &>/dev/null &
 ./ws_client.sh data  &>/dev/null &
 ./ws_client.sh control  &>/dev/null &
 ./ws_client.sh control  &>/dev/null &
 ./ws_client.sh control  &>/dev/null &
 ./ws_client.sh data  &>/dev/null &
 ./ws_client.sh control  &>/dev/null &
 ./ws_client.sh control  &>/dev/null &
 ./ws_client.sh abstract  &>/dev/null &
 ./ws_client.sh data  &>/dev/null &
 ./ws_client.sh control  &>/dev/null &
 ./ws_client.sh abstract  &>/dev/null &
 ./ws_client.sh data  &>/dev/null &
 ./ws_client.sh control  &>/dev/null &
 ./ws_client.sh control  &>/dev/null &
 ./ws_client.sh data  &>/dev/null &
 ./ws_client.sh control  &>/dev/null &
 ./ws_client.sh control  &>/dev/null &
 ./ws_client.sh control  &>/dev/null &
 ./ws_client.sh data  &>/dev/null &
 ./ws_client.sh control  &>/dev/null &

